[build-system]
requires = ["setuptools ~= 58.0", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "spatialtis/_version.py"
version_scheme = "release-branch-semver"